name: Send Notifications to Slack
on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  issue-notifications:
    name: Send Notifications
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        id: sanitize-title
        with:
          script: |
            const payload = github.event;
            
            // Sanitization functions
            const sanitizePayload = (payload) => {
              return title
                // Remove potential markdown formatting
                .replace(/[*_~`]/g, '')
                // Remove potential HTML tags
                .replace(/<[^>]*>/g, '')
                // Remove multiple spaces
                .replace(/\s+/g, ' ')
                // Trim whitespace
                .trim()
                // Limit length
                .substring(0, 100);
            };
            
            // Escape special characters for Slack
            const escapeForSlack = (text) => {
              return text
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;');
            };
            
            const sanitizedPayload = escapeForSlack(sanitizePayload(payload));
            core.setOutput('safe-payload', sanitizedPayload);
      - name: Send notifications on Pull Request
        if: ${{ github.event_name == 'pull_request'}}
        id: slack_PR
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "Notification Type": "Pull Request",
              "Notification URL":"${{ github.event.pull_request.html_url }}",
              "GitHub Repo": "${{ github.repository }}",
              "Notification Title": "${{ steps.sanitize-title.outputs.safe-payload }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send notification on new issues
        if: ${{github.event_name == 'issues'}}
        id: slack_issue
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "Notification Type": "Issue",
              "Notification URL":"${{ github.event.issue.html_url }}",
              "GitHub Repo": "${{ github.repository }}",
              "Notification Title": "${{ github.event.issue.title }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send notification on Issues and Pull Requests Comments
        if: ${{github.event_name == 'issue_comment'}}
        id: slack_issue_comment
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "Notification Type": "Issue comment",
              "Notification URL":"${{ github.event.comment.html_url }}",
              "GitHub Repo": "${{ github.repository }}",
              "Notification Title": "${{ github.event.issue_comment.issue.title }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
